from sortedcontainers import SortedDict

# Create a SortedDict (TreeMap equivalent in Python)
buildings = SortedDict()

# Populate the SortedDict with building numbers as keys and building names as values
buildings[1] = "Administration Building"
buildings[4] = "ROTC Building"
buildings[5] = "Academic Office Building, College of Business, Social Sciences"
buildings[7] = "Electrical Energy Resources Centre"
buildings[8] = "Dow Environmental Sciences & Engineering Building"
buildings[9] = "Alumni House, Advancement & Alumni Engagement"
buildings[10] = "Rozsa Center for the Performing Arts"
buildings[11] = "Walker Hall"
buildings[12] = "Minerals & Materials Engineering Building"
buildings[13] = "Center for Diversity & Inclusion"
buildings[14] = "Grover C. Dillman Hall"
buildings[15] = "Fisher"
buildings[16] = "Public Safety & Police Services"
buildings[17] = "J. R. Van Pelt & John & Ruanne Opie Library"
buildings[18] = "U. J. Noblet Forestry Building"
buildings[19] = "Chemical Sciences & Engineering Building"
buildings[20] = "R. L. Smith MEEM"
buildings[24] = "Student Development Complex"
buildings[25] = "Kearly Stadium Press Box"
buildings[28] = "Kanwal & Ann Rekhi Hall"
buildings[30] = "Little Huskies Child Development Center"
buildings[31] = "Douglass Houghton Hall"
buildings[32] = "Daniell Heights Apartments"
buildings[34] = "Memorial Union Building"
buildings[37] = "Wadsworth Hall"
buildings[38] = "West McNair Hall"
buildings[40] = "East McNair Hall"
buildings[44] = "Facilities Management, Husky Motors"
buildings[45] = "Sustainability Demonstration House"
buildings[48] = "Hillside Place"
buildings[50] = "Gates Tennis Center"
buildings[51] = "Grad Commons"
buildings[82] = "Transfer House"
buildings[84] = "Harold Meese Center, Psychology & Human Factors"
buildings[95] = "Advanced Technology Development Complex"
buildings[100] = "Great Lakes Research Center"
buildings[103] = "A. E. Seaman Mineral Museum"
buildings[107] = "Peace Corps Master's International House"
buildings[114] = "H-STEM Building"
buildings[119] = "East Hall—Opening Fall 2025"

